version: '3.1'
services:
  db1:
    image: postgres:13.5
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: server-nestjs
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
