export enum ErrorType {
  VALIDATION = 'VALIDATION',
  BUSINESS = 'BUSINESS',
  COMMON = 'COMMON',
}

export enum ErrorMessageKey {
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  UNAUTHORIZED_ERROR = 'UNAUTHORIZED_ERROR',
  NOT_FOUND_ERROR = 'NOT_FOUND_ERROR',
  CONFLICT_ERROR = 'CONFLICT_ERROR',
  FORBIDDEN_ERROR = 'FORBIDDEN_ERROR',
  EXPIRED_TOKEN_ERROR = 'EXPIRED_TOKEN_ERROR',
  ARGUMENTS_ERROR = 'ARGUMENTS_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  EMPTY_ERROR = 'EMPTY_ERROR',
  ACCOUNT_SUSPEN_ERROR = 'ACCOUNT_SUSPEN_ERROR',
  ACCOUNT_LOGOUT_ERROR = 'ACCOUNT_LOGOUT_ERROR',
}
